var annotated_dup =
[
    [ "vkdb", null, [
      [ "AddQuery", "structvkdb_1_1AddQuery.html", "structvkdb_1_1AddQuery" ],
      [ "AllClause", "structvkdb_1_1AllClause.html", "structvkdb_1_1AllClause" ],
      [ "AtClause", "structvkdb_1_1AtClause.html", "structvkdb_1_1AtClause" ],
      [ "BetweenClause", "structvkdb_1_1BetweenClause.html", "structvkdb_1_1BetweenClause" ],
      [ "BloomFilter", "classvkdb_1_1BloomFilter.html", "classvkdb_1_1BloomFilter" ],
      [ "CreateQuery", "structvkdb_1_1CreateQuery.html", "structvkdb_1_1CreateQuery" ],
      [ "Database", "classvkdb_1_1Database.html", "classvkdb_1_1Database" ],
      [ "DataPoint", "structvkdb_1_1DataPoint.html", "structvkdb_1_1DataPoint" ],
      [ "DataRange", "classvkdb_1_1DataRange.html", "classvkdb_1_1DataRange" ],
      [ "DeleteQuery", "structvkdb_1_1DeleteQuery.html", "structvkdb_1_1DeleteQuery" ],
      [ "DropQuery", "structvkdb_1_1DropQuery.html", "structvkdb_1_1DropQuery" ],
      [ "FriendlyQueryBuilder", "classvkdb_1_1FriendlyQueryBuilder.html", "classvkdb_1_1FriendlyQueryBuilder" ],
      [ "Interpreter", "classvkdb_1_1Interpreter.html", "classvkdb_1_1Interpreter" ],
      [ "Lexer", "classvkdb_1_1Lexer.html", "classvkdb_1_1Lexer" ],
      [ "LRUCache", "classvkdb_1_1LRUCache.html", "classvkdb_1_1LRUCache" ],
      [ "LSMTree", "classvkdb_1_1LSMTree.html", "classvkdb_1_1LSMTree" ],
      [ "MemTable", "classvkdb_1_1MemTable.html", "classvkdb_1_1MemTable" ],
      [ "MetricExpr", "structvkdb_1_1MetricExpr.html", "structvkdb_1_1MetricExpr" ],
      [ "ParseError", "classvkdb_1_1ParseError.html", null ],
      [ "Parser", "classvkdb_1_1Parser.html", "classvkdb_1_1Parser" ],
      [ "Printer", "classvkdb_1_1Printer.html", "classvkdb_1_1Printer" ],
      [ "PutQuery", "structvkdb_1_1PutQuery.html", "structvkdb_1_1PutQuery" ],
      [ "QueryBuilder", "classvkdb_1_1QueryBuilder.html", "classvkdb_1_1QueryBuilder" ],
      [ "RemoveQuery", "structvkdb_1_1RemoveQuery.html", "structvkdb_1_1RemoveQuery" ],
      [ "RuntimeError", "classvkdb_1_1RuntimeError.html", "classvkdb_1_1RuntimeError" ],
      [ "SelectQuery", "structvkdb_1_1SelectQuery.html", "structvkdb_1_1SelectQuery" ],
      [ "SelectTypeAvgExpr", "structvkdb_1_1SelectTypeAvgExpr.html", "structvkdb_1_1SelectTypeAvgExpr" ],
      [ "SelectTypeCountExpr", "structvkdb_1_1SelectTypeCountExpr.html", "structvkdb_1_1SelectTypeCountExpr" ],
      [ "SelectTypeDataExpr", "structvkdb_1_1SelectTypeDataExpr.html", "structvkdb_1_1SelectTypeDataExpr" ],
      [ "SelectTypeMaxExpr", "structvkdb_1_1SelectTypeMaxExpr.html", "structvkdb_1_1SelectTypeMaxExpr" ],
      [ "SelectTypeMinExpr", "structvkdb_1_1SelectTypeMinExpr.html", "structvkdb_1_1SelectTypeMinExpr" ],
      [ "SelectTypeSumExpr", "structvkdb_1_1SelectTypeSumExpr.html", "structvkdb_1_1SelectTypeSumExpr" ],
      [ "SSTable", "classvkdb_1_1SSTable.html", "classvkdb_1_1SSTable" ],
      [ "Table", "classvkdb_1_1Table.html", "classvkdb_1_1Table" ],
      [ "TableNameExpr", "structvkdb_1_1TableNameExpr.html", "structvkdb_1_1TableNameExpr" ],
      [ "TablesQuery", "structvkdb_1_1TablesQuery.html", "structvkdb_1_1TablesQuery" ],
      [ "TagColumnsExpr", "structvkdb_1_1TagColumnsExpr.html", "structvkdb_1_1TagColumnsExpr" ],
      [ "TagExpr", "structvkdb_1_1TagExpr.html", "structvkdb_1_1TagExpr" ],
      [ "TagKeyExpr", "structvkdb_1_1TagKeyExpr.html", "structvkdb_1_1TagKeyExpr" ],
      [ "TagListExpr", "structvkdb_1_1TagListExpr.html", "structvkdb_1_1TagListExpr" ],
      [ "TagValueExpr", "structvkdb_1_1TagValueExpr.html", "structvkdb_1_1TagValueExpr" ],
      [ "TimeSeriesKey", "classvkdb_1_1TimeSeriesKey.html", "classvkdb_1_1TimeSeriesKey" ],
      [ "TimestampExpr", "structvkdb_1_1TimestampExpr.html", "structvkdb_1_1TimestampExpr" ],
      [ "Token", "classvkdb_1_1Token.html", "classvkdb_1_1Token" ],
      [ "ValueExpr", "structvkdb_1_1ValueExpr.html", "structvkdb_1_1ValueExpr" ],
      [ "VQ", "classvkdb_1_1VQ.html", "classvkdb_1_1VQ" ],
      [ "WALRecord", "structvkdb_1_1WALRecord.html", null ],
      [ "WhereClause", "structvkdb_1_1WhereClause.html", "structvkdb_1_1WhereClause" ],
      [ "WriteAheadLog", "classvkdb_1_1WriteAheadLog.html", "classvkdb_1_1WriteAheadLog" ]
    ] ]
];