name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install graphviz -y

      - name: Install Doxygen 1.12.0
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.12.0"

      - name: Generate Docs
        run: |
          cd docs
          doxygen Doxyfile

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs/html
