name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate Docs
        run: |
          cd docs
          doxygen Doxyfile

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs/html
