name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install graphviz -y

      - name: Install Latest Stable Doxygen
        run: |
          curl -s https://api.github.com/repos/doxygen/doxygen/releases/latest \
            | grep "browser_download_url.*linux.bin.tar.gz" \
            | cut -d '"' -f 4 \
            | wget -qi -
          tar -xvf doxygen-*.linux.bin.tar.gz
          sudo mv doxygen-*/bin/* /usr/local/bin/
          sudo mv doxygen-*/share/* /usr/local/share/
          doxygen --version

      - name: Generate Docs
        run: |
          cd docs
          doxygen Doxyfile

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs/html
