name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up CMake
        uses: lukka/get-cmake

      - name: Build and run tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./tests/vkdb_tests