name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Build and run tests
        run: |
          sudo apt install gcc-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10
          sudo update-alternatives --config gcc
          mkdir -p build
          cd build
          cmake ..
          make
          ./tests/vkdb_tests